# Generated by Django 4.1.4 on 2023-01-25 16:55

import django.db.models.deletion
from django.db import migrations, models

import applicating.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("phonecode", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="EnglishReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="EnglishTalking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="EnglishWriting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="InterestIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="InterestSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Modality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=128)),
                ("displayname", models.CharField(max_length=64)),
                ("fullname", models.CharField(max_length=128)),
                ("whatsappnumber", models.PositiveIntegerField()),
                ("residencecity", models.CharField(max_length=64)),
                ("allow_to_travel_country", models.BooleanField()),
                ("allow_to_travel_city", models.BooleanField()),
                ("role_frontend", models.BooleanField()),
                ("role_backend", models.BooleanField()),
                ("role_fullstack", models.BooleanField()),
                ("role_mobile", models.BooleanField()),
                ("role_qatesting", models.BooleanField()),
                ("role_softwarearchitect", models.BooleanField()),
                ("role_enterprisesolutiondeveloper", models.BooleanField()),
                ("role_businessanalytics", models.BooleanField()),
                ("role_qasecurity", models.BooleanField()),
                ("role_solutionarchitect", models.BooleanField()),
                ("role_cloudarchitect", models.BooleanField()),
                ("role_devops", models.BooleanField()),
                ("role_productmanager", models.BooleanField()),
                ("role_productowner", models.BooleanField()),
                ("role_scrummaster", models.BooleanField()),
                ("role_agilecoach", models.BooleanField()),
                ("role_dataengineer", models.BooleanField()),
                ("role_datamodeler", models.BooleanField()),
                ("role_datascience", models.BooleanField()),
                ("role_machinelearning", models.BooleanField()),
                ("role_designresearch", models.BooleanField()),
                ("role_uxuidesigner", models.BooleanField()),
                ("role_uxwriter", models.BooleanField()),
                ("role_cxdesigner", models.BooleanField()),
                ("role_graphicaldesigner", models.BooleanField()),
                ("role_campaingmanager", models.BooleanField()),
                ("role_creativewriter", models.BooleanField()),
                ("role_growthmarketer", models.BooleanField()),
                ("role_businessdeveloper", models.BooleanField()),
                ("role_accountmanager", models.BooleanField()),
                ("amount_minimum", models.PositiveIntegerField()),
                ("amount_wished", models.PositiveIntegerField()),
                (
                    "resume",
                    models.FileField(
                        blank=True, upload_to=applicating.models.resumepath
                    ),
                ),
                (
                    "network_linkedin",
                    models.URLField(blank=True, max_length=128),
                ),
                ("network_github", models.URLField(blank=True, max_length=128)),
                (
                    "network_behance",
                    models.URLField(blank=True, max_length=128),
                ),
                (
                    "network_website",
                    models.URLField(blank=True, max_length=128),
                ),
                (
                    "availability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicating.availability",
                    ),
                ),
                (
                    "english_reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicating.englishreading",
                    ),
                ),
                (
                    "english_talking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicating.englishtalking",
                    ),
                ),
                (
                    "english_writing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicating.englishwriting",
                    ),
                ),
                (
                    "interest_industry",
                    models.ManyToManyField(to="applicating.interestindustry"),
                ),
                (
                    "interest_subject",
                    models.ManyToManyField(to="applicating.interestsubject"),
                ),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicating.modality",
                    ),
                ),
                (
                    "residencecountry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="residencecountry_applicant_set",
                        to="applicating.country",
                    ),
                ),
                (
                    "whatsappprefix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsappprefix_applicant_set",
                        to="applicating.country",
                    ),
                ),
            ],
        ),
    ]
