# Generated by Django 4.0.3 on 2022-04-25 18:57

from typing import List

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def MigratePermissions(apps, schema_editor):
  Permission = apps.get_model('auth', 'Permission')
  User = apps.get_model('auth', 'User')
  ContentType = apps.get_model('contenttypes', 'ContentType')

  content_type = ContentType.objects.get_for_model(User)

  Permission.objects.bulk_create([
    Permission(codename='im_hunter',
               name='Can access Hunter views',
               content_type=content_type),
    Permission(codename='im_candidate',
               name='Can access Candidate views',
               content_type=content_type),
    Permission(codename='im_accountmanager',
               name='Can access Account Manager views',
               content_type=content_type),
    Permission(codename='im_freelancer',
               name='Can access Freelancer views',
               content_type=content_type),
    Permission(codename='im_staff',
               name='Can access Staff views',
               content_type=content_type),
  ])


def ReversePermissions(apps, schema_editor):
  Permission = apps.get_model('auth', 'Permission')
  Permission.objects.filter(codename__startswith='im_').delete()


def MigrateSkillTree(apps, schema_editor):
  FreelancerSkill = apps.get_model('sinek', 'FreelancerSkill')

  n1 = _createGroup(FreelancerSkill, 'Creatividad y diseño', None)
  n22 = _createGroup(FreelancerSkill, 'Logo e identidad', n1)
  _createChildren(FreelancerSkill, n22, [
    'Naming',
    'Diseño de logo',
    'Diseño de identidad visual y brandbook',
    'Diseño de tarjetas de presentación',
    'Estudio y conceptualización de marca',
    'Estrategia de Marca'])
  n22 = _createGroup(FreelancerSkill, 'Arte e ilustración', n1)
  _createChildren(FreelancerSkill, n22, [
    'Ilustración corporativa',
    'Ilustración para libros',
    'Storyboards',
    'Caricaturas',
    'Infografías',
    'Graffitis',
    'Diseño de personajes'])
  n22 = _createGroup(FreelancerSkill, 'Dirección creativa', n1)
  _createChildren(FreelancerSkill, n22, [
    'Auditoría Digital',
    'Dirección creativa para campañas 360',
    'Dirección creativa de eventos',
    'Dirección creativa audiovisual',
    'Dirección creativa musical'])
  n22 = _createGroup(FreelancerSkill, 'Diseño gráfico corporativo', n1)
  _createChildren(FreelancerSkill, n22, [
    'Diseño de empaques - Packaging',
    'Diseño de etiquetas',
    'Diseño editorial',
    'Diseño de presentaciones',
    'Diseño de menú (restaurants)'])
  n22 = _createGroup(FreelancerSkill, 'Diseño publicitario', n1)
  _createChildren(FreelancerSkill, n22, [
    'Diseño de merchandising',
    'Diseño de brochures',
    'Diseño de flyers informativos',
    'Diseño de Banners',
    'Diseño de catálogos',
    'Diseño y edición de imágenes',
    'Diseño para social media'])
  n22 = _createGroup(FreelancerSkill, 'Fotografía', n1)
  _createChildren(FreelancerSkill, n22, [
    'Fotografía para redes sociales',
    'Fotografía de productos',
    'Fotografía de prendas y zapatería',
    'Fotografía de modelos',
    'Fotografía gastronómica',
    'Fotografía de bebés',
    'Retratos familiares',
    'Fotografía de matrimonios',
    'Fotografía de eventos',
    'Fotografía corporativa',
    'Fotografías 360º',
    'Fotografía industrial',
    'Fotografía publicitaria',
    'Retoque de fotografía digital'])
  n22 = _createGroup(FreelancerSkill, 'Video', n1)
  _createChildren(FreelancerSkill, n22, [
    'Videos corporativos para empresas',
    'Producción y post-producción de videos',
    'Servicio de grabación de video 360º',
    'Videos publicitarios',
    'Videos animados',
    'Elaboración de tutoriales',
    'Cortometrajes',
    'Producción de audio',
    'Edición de vídeo',
    'Grabación de video',
    'Dirección de vídeo'])
  n22 = _createGroup(FreelancerSkill, '3D', n1)
  _createChildren(FreelancerSkill, n22, [
    'Diseño en 3D',
    'Modelado en 3D',
    'Renderizado en 3D',
    'Animación en 3D',
    'Fotografía y recorridos 3D',
    'Arquitectura comercial',
    'Showrooms'])
  n22 = _createGroup(FreelancerSkill, 'Audio', n1)
  _createChildren(FreelancerSkill, n22, [
    'Doblaje español-inglés',
    'Doblaje inglés-español',
    'Voz en off',
    'Voz para publicidad',
    'Songwriting',
    'Composición musical',
    'Producción musical',
    'DJ',
    'Vocalista',
    'Creación de jingles publicitario',
    'Creación de intros musicales',
    'Elaboración de podcasts',
    'Efectos de sonido',
    'Producción de audiolibros'])
  n22 = _createGroup(
    FreelancerSkill,
    'Videojuegos y Realidad aumentada y virtual',
    n1)
  _createChildren(FreelancerSkill, n22, [
    'Experiencias publicitarias en Realidad Aumentada',
    'Experiencias publicitarias en Realidad Virtual',
    'Videojuegos publicitarios web 2D',
    'Videojuegos publicitarios para activaciones',
    'Videojuegos publicitarios 3D'])

  n1 = _createGroup(FreelancerSkill, 'Redacción', None)
  _createChildren(FreelancerSkill, n1, [
    'Artículos y publicaciones de blog',
    'Escritura del curriculum vitae',
    'Corrección de textos y edición',
    'Escritura técnica',
    'Cartas de presentación',
    'Perfiles de LinkedIn',
    'UX Writing',
    'Copywriting',
    'Ghostwriting',
    'Investigación y resúmenes',
    'Descripciones de productos',
    'Contenido de sitio web',
    'Escritura de guiones',
    'Redacción de discursos',
    'Redacción de podcasts',
    'Creación de diálogos',
    'Corrección de estilo',
    'Escritura de artículos',
    'Escritura creativa'])

  n1 = _createGroup(FreelancerSkill, 'Traducción', None)
  _createChildren(FreelancerSkill, n1, [
    'Traducción inglés-español',
    'Traducción español-inglés',
    'Traducción español-quechua'])

  n1 = _createGroup(FreelancerSkill, 'Marketing Digital', None)
  n22 = _createGroup(FreelancerSkill, 'Consultoría', n1)
  _createChildren(FreelancerSkill, n22, [
    'Estrategia de marca',
    'Estrategia de engagement',
    'Diseño de planes de acción en redes',
    'Manejo de crisis reputacional',
    'Estrategia de inbound Marketing',
    'Estrategia see think do care',
    'Estrategia AIDA',
    'Estrategia de contenidos',
    'Consultoría SEO',
    'Auditoría SEO'])
  n22 = _createGroup(FreelancerSkill, 'Generación de Tráfico', n1)
  _createChildren(FreelancerSkill, n22, [
    'Generación de contenido',
    'Redacción de artículos SEO',
    'Producción de contenido audiovisual',
    'E-mailing',
    'Email Remarketing',
    'Retargeting a website',
    'Retargeting a productos visitados e-commerce',
    'Activaciones digitales',
    'Facebook Ads',
    'Google Ads',
    'Linkedin Ads',
    'Tinder Ads',
    'TikTok Ads',
    'Twitch Ads',
    'Youtube Ads',
    'Publicidad programática'])
  n22 = _createGroup(FreelancerSkill, 'Medición y optimización', n1)
  _createChildren(FreelancerSkill, n22, [
    'Media Tracking',
    'A/B Testing',
    'ROI',
    'Facebook insight',
    'Google Analytics',
    'Google Data Studio',
    'Hootsuite',
    'RD  Station',
    'Hubspot'])
  n22 = _createGroup(FreelancerSkill, 'Posicionamiento SEO', n1)
  _createChildren(FreelancerSkill, n22, [
    'SEO Técnico, etiquetas, sitemaps, robots.txt',
    'Index optimization',
    'SEO Local',
    'SEO Ecommerce',
    'SEO para Startups',
    'SEO Internacional ',
    'SEO para marca personal'])
  n22 = _createGroup(FreelancerSkill, 'Social Media', n1)
  _createChildren(FreelancerSkill, n22, [
    'Community Management',
    'Social listening avanzado'])
  _createChildren(FreelancerSkill, n1, [
    'Growth Hacking',
    'Chatbots',
    'PR y Marketing de influencers'])

  n1 = _createGroup(FreelancerSkill, 'Diseño de experiencia digital', None)
  n22 = _createGroup(FreelancerSkill, 'Consultoría', n1)
  _createChildren(FreelancerSkill, n22, [
    'Estrategia de producto',
    'Estrategia de adopción de usuarios',
    'Estrategia de contenido',
    'Entrenamiento de personal'])
  n22 = _createGroup(FreelancerSkill, 'Levantamiento de procesos', n1)
  _createChildren(FreelancerSkill, n22, [
    'Modelado de procesos',
    'Optimización de procesos'])
  n22 = _createGroup(FreelancerSkill, 'Diseño de servicio y producto', n1)
  _createChildren(FreelancerSkill, n22, [
    'Lean StartUp',
    'Investigación estadística',
    'Investigación de escritorio',
    'Investigación netnográfica',
    'Identificación de insights',
    'Definición de problema(s)',
    'Elaboración de árbol de problemas',
    'Elaboración de Benchmark',
    'Construcción de Buyer Persona',
    'Construcción de Customer Journey Maps',
    'Elaboración de Service Blueprint',
    'Ideación y diseño de experiencia TOBE',
    'Validación de ideas con usuarios',
    'Realización de Focus Groups',
    'Generación de modelos de negocio',
    'Sprint Design',
    'Agile Inception DECK',
    'Diseño de métricas e indicadores',
    'Método HEART'])
  n22 = _createGroup(FreelancerSkill, 'Implementación UX', n1)
  _createChildren(FreelancerSkill, n22, [
    'Diseño y prototipado UX de aplicaciones móviles',
    'Diseño y prototipado UX de aplicaciones web',
    'Diseño y prototipado UX de websites corporativos',
    'Diseño y prototipado UX de e-commerce',
    'Pruebas de usabilidad con usuarios',
    'Testing A/B',
    'Auditoría UX'])
  n22 = _createGroup(FreelancerSkill, 'Diseño de interfaces', n1)
  _createChildren(FreelancerSkill, n22, [
    'Diseño UI de landing pages',
    'Diseño UI de aplicaciones móviles',
    'Diseño UI de aplicaciones web',
    'Diseño UI de websites corporativos',
    'Diseño UI de ecommerce',
    'Elaboración de guía de estilos digital',
    'Creación de íconos',
    'Elaboración de tutoriales',
    'Elaboración de documentos funcionales',
    'Elaboración de product backlog'])

  n1 = _createGroup(FreelancerSkill, 'Desarrollo web', None)
  n22 = _createGroup(FreelancerSkill, 'Websites Corporativos CMS', n1)
  _createChildren(FreelancerSkill, n22, [
    'Wordpress',
    'Drupal',
    'Joomla',
    'Acquia',
    'Magnolia'])
  n22 = _createGroup(FreelancerSkill, 'LMS - Learning Management System', n1)
  _createChildren(FreelancerSkill, n22, [
    'Moodle',
    'Blackboard',
    'Chamilo',
    'Docebo',
    'Mindflash',
    'Plugins de Wordpress',
    'Open edX ',
    'Canvas',
    'Talent LMS'])
  n22 = _createGroup(FreelancerSkill, 'CRM', n1)
  _createChildren(FreelancerSkill, n22, [
    'Salesforce',
    'Hubspot',
    'Britix24',
    'Odoo CRM',
    'Sugar CRM',
    'Suite CRM',
    'Vtiger CRM',
    'Dolibarr'])
  n22 = _createGroup(FreelancerSkill, 'Intranets y sistemas colaborativos', n1)
  n333 = _createGroup(FreelancerSkill, 'Sharepoint', n22)
  _createChildren(FreelancerSkill, n333, [
    'SharePoint 2010',
    'SharePoint 2013',
    'SharePoint 2016',
    'SharePoint 2019',
    'SharePoint Online'])
  _createChildren(FreelancerSkill, n22, [
    'Bitrix24 ',
    'dotCMS',
    'TWiki ',
    'Liferay ',
    'EXO',
    'Precurio ',
    'Quintagroup',
    'Engynn',
    'Intranet basada en Drupal',
    'Intranet basada en Wordpress'])
  n22 = _createGroup(FreelancerSkill, 'Website Builders', n1)
  _createChildren(FreelancerSkill, n22, [
    'Wix',
    'Godaddy website builder',
    'Wordpress website builder',
    'Squarespace',
    'Blogger'])
  n22 = _createGroup(FreelancerSkill, 'Ecommerce CMS', n1)
  _createChildren(FreelancerSkill, n22, [
    'Woocommerce',
    'Prestashop',
    'Magento',
    'Shopify',
    'IBM WebSphere Commerce',
    'Oracle ATG',
    'SAP Hybris',
    'VTEX',
    'Análisis de performance y seguridad'])

  n1 = _createGroup(FreelancerSkill, 'Desarrollo de sistemas a medida', None)
  n22 = _createGroup(FreelancerSkill, 'Aplicativos Móviles', n1)
  n333 = _createGroup(FreelancerSkill, 'Desarrollo Nativo en Android', n22)
  _createChildren(FreelancerSkill, n333, [
    'Java',
    'Kotlin'])
  n333 = _createGroup(FreelancerSkill, 'Desarrollo Nativo en iOS', n22)
  _createChildren(FreelancerSkill, n333, [
    'Objective-C',
    'Swift'])
  _createChildren(FreelancerSkill, n22, [
    'Phonegap',
    'Xamarin',
    'React Native',
    'Flutter'])
  n22 = _createGroup(FreelancerSkill, 'Frontend web', n1)
  _createChildren(FreelancerSkill, n22, [
    'Angular JS',
    'Angular CLI',
    'Knockout',
    'ReactJS',
    'Vue JS',
    'Vue CLI'])
  n22 = _createGroup(FreelancerSkill, 'Backend y fullstack', n1)
  n333 = _createGroup(FreelancerSkill, '.NET', n22)
  _createSkill(
    FreelancerSkill,
    'Consultoría en arquitectura de aplicaciones en .NET',
    n333)
  n4444 = _createGroup(FreelancerSkill, 'Lenguaje de programación', n333)
  _createChildren(FreelancerSkill, n4444, [
    'C#',
    'C++',
    'Visual Basic'])
  n4444 = _createGroup(FreelancerSkill, 'Versión del Framework', n333)
  _createChildren(FreelancerSkill, n4444, [
    '.NET 2.0',
    '.NET 3',
    '.NET 4',
    '.NET 4.5 ',
    '.NET 4.6',
    '.NET 4.7',
    '.NET 4.8',
    '.NET Core'])
  n333 = _createGroup(FreelancerSkill, 'Java', n22)
  _createChildren(FreelancerSkill, n333, [
    'Consultoría en arquitectura de aplicaciones en JAVA',
    'Java Spring Web',
    'Java Spring Boot',
    'Java JPA',
    'Java JDO',
    'Java JUnit'])
  n333 = _createGroup(FreelancerSkill, 'PHP', n22)
  _createChildren(FreelancerSkill, n333, [
    'Consultoría en arquitectura de aplicaciones en PHP',
    'Laravel',
    'Symfony',
    'CodeIgniter',
    'Zend Framewor',
    'Yii (Framework)',
    'CakePHP',
    'Slim',
    'Phalcon',
    'FuelPHP',
    'Fat-Free Framework'])
  n333 = _createGroup(FreelancerSkill, 'Python', n22)
  _createChildren(FreelancerSkill, n333, [
    'Python Django',
    'Python CherryPy',
    'Python Tornado',
    'Python SqlAlchemy',
    'Python Jinja2'])

  _createSkill(FreelancerSkill, 'Ruby on rails', n22)
  n333 = _createGroup(FreelancerSkill, 'NodeJS', n22)
  _createChildren(FreelancerSkill, n333, [
    'NodeJS Express',
    'NodeJS Mongoose',
    'NodeJS Vanilla'])

  n22 = _createGroup(FreelancerSkill, 'Gestor de bases de datos SQL', n1)
  _createChildren(FreelancerSkill, n22, [
    'MySQL',
    'Maria DB'])
  n333 = _createGroup(FreelancerSkill, 'PostgreSQL', n22)
  _createChildren(FreelancerSkill, n333, [
    'PostgreSQL Versión 9',
    'PostgreSQL Versión 10',
    'PostgreSQL Versión 11'])
  n333 = _createGroup(FreelancerSkill, 'MSSQL Server', n22)
  _createChildren(FreelancerSkill, n333, [
    'SQL Server 2008',
    'SQL Server 2008 R2',
    'SQL Server 2012',
    'SQL Server 2014',
    'SQL Server 2016',
    'SQL Server 2017',
    'SQL Server 2019'])
  n333 = _createGroup(FreelancerSkill, 'Oracle', n22)
  _createChildren(FreelancerSkill, n333, [
    'Oracle Database 11g',
    'Oracle Database 12c',
    'Oracle Database 18c',
    'Oracle Database 19c',
    'Oracle Database 21c'])
  n22 = _createGroup(FreelancerSkill, 'Gestor de bases de datos NoSQL', n1)
  _createChildren(FreelancerSkill, n22, [
    'MongoDB',
    'Cassandra',
    'Redis',
    'CouchDB',
    'Node4J',
    'Hazelcast'])
  n22 = _createGroup(FreelancerSkill, 'Gestor de despliegues', n1)
  _createChildren(FreelancerSkill, n22, [
    'Kubernetes',
    'Docker',
    'Jenkins'])

  n1 = _createGroup(FreelancerSkill, 'Programación avanzada', None)
  _createChildren(FreelancerSkill, n1, [
    'Linux development'
    'Assembler development',
    'Algoritmia avanzada para soluciones industriales',
    'Algoritmia avanzada para soluciones comerciales',
    'Matemáticas aplicada a la industria',
    'Inteligencia artificial',
    'Machine learning',
    'Deep learning'])

  n1 = _createGroup(FreelancerSkill, 'Integraciones con ERP', None)
  #_createSkill(FreelancerSkill, 'Integración con Microsoft Dynamics', n1)
  n22 = _createGroup(FreelancerSkill, 'Integración con Oracle', n1)
  _createChildren(FreelancerSkill, n22, [
    'JD Edwards Enterprise One',
    'Oracle People Soft',
    'Oracle E-Business One'])
  #_createSkill(FreelancerSkill, 'Integración con Infor', n1)
  n22 = _createGroup(FreelancerSkill, 'Integración con SAP', n1)
  _createChildren(FreelancerSkill, n22, [
    'SAP ABAP',
    'SAP Fiori',
    'SAPUI5'])
  n333 = _createGroup(FreelancerSkill, 'Módulos de SAP R3', n22)
  _createChildren(FreelancerSkill, n333, [
    'FI: (Finanzas) Contabilidad Financiera',
    'CO: (Controlling) Control y Costos',
    'LO: (Logistics) Logística general',
    'SD: (Sales and Distribution) Ventas y Distribución',
    'MM: (Materials Management) Gestión de Materiales',
    'LE: (Logistics Execution) Ejecución de logística',
    'PP: (Production Planning) Planificación de la producción',
    'PS: (Project system) Sistema de Proyectos',
    'QM (Quality Management) Gestión de calidad',
    'HR (Human Resources) Recursos Humanos',
    'BC Basis Components'])
  n333 = _createGroup(
    FreelancerSkill,
    'Módulos de SAP S/4 HANA Enterprise Management',
    n22)
  _createChildren(FreelancerSkill, n333, [
    'Asset Management (Gestión de activos)',
    'Finance (Finanzas)',
    'Human Resources (Recursos humanos)',
    'Manufacturing (Fabricación)',
    'Maintenance, Repair, and Overhaul (Mantenimiento, reparación y revisión)',
    'R&D / Engineering (I+D / Ingeniería)',
    'Sales (Ventas)',
    'Service (Servicios)',
    'Supply Chain (Cadena de suministro)',
    'Analytics Technology (Tecnología analítica)',
    'Enterprise Technology (Tecnología empresarial)',
    'Projects (Proyectos)'])
  n333 = _createGroup(
    FreelancerSkill,
    'Módulos de SAP S/4 HANA LoB Products',
    n22)
  _createChildren(FreelancerSkill, n333, [
    'Asset Management (Gestión de activos)',
    'Database and Data Management (Base de datos y gestión de datos)',
    'Finance (Finanzas)',
    'Manufacturing (Fabricación)',
    'R&D / Engineering (I+D / Ingeniería)',
    'Sales (Ventas)',
    'Supply Chain (Cadena de suministro)',
    'Enterprise Technology (Tecnología empresarial)'])
  n333 = _createGroup(
    FreelancerSkill,
    'SAP S/4 HANA LoB Products para industrias específicas',
    n22)
  _createChildren(FreelancerSkill, n333, [
    'Agriculture (Agricultura)',
    'Banking (La banca)',
    'Insurance (Aseguradoras)',
    'Oil & Gas (Petróleso y gas natural)',
    'Professional Services (Servicios profesionales)',
    'Public Sector (Sector público)',
    'Retail and Fashion (Retail y moda)',
    'Utilities (Servicios)',
    'SAP Waste & Recycling (Desperdicio y reciclaje)'])
  n333 = _createGroup(FreelancerSkill, 'SAP Business One', n22)
  n4444 = _createGroup(FreelancerSkill, 'Módulos', n333)
  _createChildren(FreelancerSkill, n4444, [
    'Finanzas',
    'Oportunidades',
    'Ventas',
    'Interlocutores comerciales',
    'Gestión de bancos',
    'Inventario',
    'Recursos',
    'Producción',
    'Compras',
    'Planificación de necesidades',
    'Servicio',
    'Recursos humanos',
    'Informes',
    'Gestión'])
  n4444 = _createGroup(FreelancerSkill, 'Versiones', n333)
  _createChildren(FreelancerSkill, n4444, [
    'SAP Business One 7',
    'SAP Business One 8',
    'SAP Business One 9',
    'SAP Business One 10'])

  n1 = _createGroup(
    FreelancerSkill,
    'Quality Assurance & Testing especializado',
    None)
  _createChildren(FreelancerSkill, n1, [
    'Agile testing comprobado',
    'Pruebas funcionales',
    'Pruebas de rendimiento',
    'Pruebas de estrés',
    'Pruebas de accesibilidad',
    'Pruebas de usabilidad',
    'Pruebas de seguridad',
    'Accounting and Financial Testing',
    'Ubertesting'])
  n22 = _createGroup(FreelancerSkill, 'Automatización de pruebas', n1)
  _createChildren(FreelancerSkill, n22, [
    'UiPath',
    'Selenium',
    'Appium',
    'Protractor'])

  n1 = _createGroup(FreelancerSkill, 'Data & Analytics', None)
  n22 = _createGroup(
    FreelancerSkill,
    'Estadística, minería y ciencia de datos',
    n1)
  _createChildren(FreelancerSkill, n22, [
    'SPSS',
    'Stata',
    'Lenguaje R',
    'Programación Python',
    'Programación Java',
    'Programación SQL',
    'Matlab',
    'SAS',
    'RapidMinder',
    'BigML',
    'SAS',
    'TIBCO',
    'Alteryx',
    'Knime',
    'Mathworks',
    'Hadoop',
    'Spark',
    'Hive',
    'HBase'])
  n22 = _createGroup(FreelancerSkill, 'ETL', n1)
  _createChildren(FreelancerSkill, n22, [
    'IBM Websphere DataStage',
    'Microsoft Integration Services',
    'SAP Data Integrator',
    'Cognos Decisionstream',
    'Sunopsis',
    'Apache NiFi',
    'Streamsets',
    'Apache Airflow',
    'AWS Data Pipeline',
    'AWS Glue',
    'Talend',
    'Informatica Power Center',
    'AB Initio',
    'Pentaho',
    'Azure Data Factory',
    'SAS Dataflux'])
  n22 = _createGroup(FreelancerSkill, 'Análisis y visualización de Datos', n1)
  _createChildren(FreelancerSkill, n22, [
    'SAP Business Objects',
    'Microsoft Reporting Services',
    'Microsoft Analysis Services',
    'Power BI',
    'Tableau',
    'Qlik',
    'Microstrategy',
    'Thoughtspot'])

  n1 = _createGroup(FreelancerSkill, 'Cloud', None)
  _createChildren(FreelancerSkill, n1, [
    'Google Cloud',
    'AWS',
    'Microsoft Azure',
    'Huawei Cloud'])


def _createGroup(FreelancerSkill, skill: str, parent):
  id = FreelancerSkill.objects.create(name=skill)
  if parent:
    parent.children.add(id)
  return id


def _createSkill(FreelancerSkill, skill: str, parent):
  id = FreelancerSkill.objects.create(name=skill)
  parent.children.add(id)


def _createChildren(FreelancerSkill, parent, children: List[str]):
  for child in children:
    _createSkill(FreelancerSkill, child, parent)


def ReverseSkillTree(apps, schema_editor):
  ContentType = apps.get_model('contenttypes', 'ContentType')
  ContentType.objects.filter(app_label='sinek').delete()


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='AccountManager',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=128)),
        ('email', models.CharField(db_index=True, max_length=96)),
      ],
    ),
    migrations.CreateModel(
      name='Candidate',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=128)),
        ('email', models.CharField(max_length=128)),
        ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
      ],
    ),
    migrations.CreateModel(
      name='CandidateAnchorRecord',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('candidateId', models.CharField(max_length=128)),
        ('relevant1', models.IntegerField()),
        ('relevant2', models.IntegerField()),
        ('relevant3', models.IntegerField()),
      ],
    ),
    migrations.CreateModel(
      name='CandidateComplexRecord',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('candidateId', models.CharField(max_length=128)),
        ('start', models.DateTimeField()),
        ('finish', models.DateTimeField()),
      ],
    ),
    migrations.CreateModel(
      name='CandidateDiscAnswers',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('candidateId', models.CharField(max_length=128)),
        ('number', models.IntegerField()),
        ('plus', models.CharField(max_length=1)),
        ('minus', models.CharField(max_length=1)),
      ],
    ),
    migrations.CreateModel(
      name='CandidateTMMS24Answers',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('candidateId', models.CharField(max_length=128)),
        ('number', models.IntegerField()),
        ('score', models.CharField(max_length=1)),
      ],
    ),
    migrations.CreateModel(
      name='Freelancer',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('condition', models.IntegerField(choices=[(1, 'Fulltime'), (2, 'Halftime')])),
        ('country', models.CharField(max_length=64)),
        ('location', models.CharField(max_length=128)),
        ('email', models.CharField(db_index=True, max_length=96)),
        ('name', models.CharField(max_length=128)),
        ('phone', models.CharField(max_length=64)),
      ],
    ),
    migrations.CreateModel(
      name='Hunter',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=128)),
      ],
    ),
    migrations.CreateModel(
      name='Project',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=128)),
      ],
    ),
    migrations.CreateModel(
      name='Staff',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=128)),
      ],
    ),
    migrations.CreateModel(
      name='Role',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('accountManager', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sinek.accountmanager')),
        ('candidate', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sinek.candidate')),
        ('freelancer', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sinek.freelancer')),
        ('hunter', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sinek.hunter')),
        ('staff', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sinek.staff')),
        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
      ],
    ),
    migrations.CreateModel(
      name='FreelancerSkill',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=128)),
        ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sinek.freelancerskill')),
      ],
    ),
    migrations.CreateModel(
      name='FreelancerProjectTag',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=128)),
        ('created', models.DateTimeField(auto_now_add=True)),
        ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectTags', to='sinek.freelancer')),
      ],
      options={
        'abstract': False,
      },
    ),
    migrations.CreateModel(
      name='FreelancerNetwork',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('url', models.CharField(max_length=128)),
        ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='sinek.freelancer')),
      ],
    ),
    migrations.CreateModel(
      name='FreelancerKnowledge',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=128)),
        ('value', models.IntegerField()),
        ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledges', to='sinek.freelancer')),
      ],
    ),
    migrations.CreateModel(
      name='FreelancerBusinessTag',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=128)),
        ('created', models.DateTimeField(auto_now_add=True)),
        ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessTags', to='sinek.freelancer')),
      ],
      options={
        'abstract': False,
      },
    ),
    migrations.CreateModel(
      name='CandidateComplexAnswers',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('number', models.IntegerField()),
        ('option_a', models.BooleanField()),
        ('option_b', models.BooleanField()),
        ('option_c', models.BooleanField()),
        ('complexRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexanswers_set', to='sinek.candidatecomplexrecord')),
      ],
    ),
    migrations.CreateModel(
      name='CandidateAnchorAnswers',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('number', models.IntegerField()),
        ('score', models.CharField(max_length=1)),
        ('anchorRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchoranswers_set', to='sinek.candidateanchorrecord')),
      ],
    ),
    migrations.CreateModel(
      name='Upload',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('binary', models.BinaryField()),
        ('kind', models.IntegerField(choices=[(0, 'Other'), (1, 'Cv')])),
        ('created', models.DateTimeField()),
        ('name', models.CharField(db_index=True, max_length=128)),
        ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='sinek.freelancer')),
      ],
      options={
        'unique_together': {('name', 'freelancer')},
      },
    ),
    migrations.RunPython(MigratePermissions, ReversePermissions),
    migrations.RunPython(MigrateSkillTree, ReverseSkillTree),
  ]
