# Generated by Django 4.0.3 on 2022-06-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
    ('sinek', '0003_upload_googleid_alter_upload_binary'),
  ]

  operations = [
    migrations.AlterUniqueTogether(
      name='upload',
      unique_together=set(),
    ),
  ]
