# Generated by Django 4.0.3 on 2022-07-21 15:22

from django.db import migrations, models


def MigrateFreelancerKind(apps, schema_editor):
  Freelancer = apps.get_model('sinek', 'Freelancer')
  Freelancer.objects.filter(condition=2).update(experience=2, availability=10)


class Migration(migrations.Migration):

  dependencies = [
    ('sinek', '0004_alter_upload_unique_together'),
  ]

  operations = [
    migrations.AddField(
      model_name='freelancer', name='availability',
      field=models.IntegerField(null=True),),
    migrations.AddField(
      model_name='freelancer', name='disponibility',
      field=models.IntegerField(
        choices=[(0, 'Nosettled'),
                 (1, 'Oneweek'),
                 (2, 'Twoweeks'),
                 (3, 'Threeweeks'),
                 (4, 'Onemonth')],
        default=0),),
    migrations.AddField(
      model_name='freelancer', name='expectative', field=models.CharField(
        max_length=1024, null=True),),
    migrations.AddField(
      model_name='freelancer', name='experience', field=models.IntegerField(
        choices=[(1, 'Low'),
                 (2, 'Medium'),
                 (3, 'High')],
        null=True),),
    migrations.AddField(
      model_name='freelancer', name='minimum', field=models.FloatField(
        null=True),),
    migrations.AddField(
      model_name='freelancer', name='modality', field=models.IntegerField(
        choices=[(0, 'Nosettled'),
                 (1, 'Remote'),
                 (2, 'Hybrid'),
                 (3, 'Office')],
        default=0),),
    migrations.AlterField(
      model_name='freelancer', name='condition', field=models.IntegerField(
        choices=[(0, 'Initial'),
                 (1, 'Fulltime'),
                 (2, 'Halftime'),
                 (3, 'Talent'),
                 (4, 'Talentandfulltime'),
                 (5, 'Talentandhalftime')]),),
    migrations.RunPython(MigrateFreelancerKind), ]
