# Generated by Django 4.0.3 on 2022-08-09 15:22

from django.db import migrations
from typing import List


def MigrateDeleteFreelancerKnowledges(apps, schema_editor):
  FreelancerKnowledge = apps.get_model('sinek', 'FreelancerKnowledge')
  FreelancerKnowledge.objects.all().delete()


def MigrateDeleteTreeSkills(apps, schema_editor):
  TreeSkills = apps.get_model('sinek', 'FreelancerSkill')
  TreeSkills.objects.all().delete()


def MigrateSkillTree(apps, schema_editor):
  FreelancerSkill = apps.get_model('sinek', 'FreelancerSkill')

  n1 = _createGroup(FreelancerSkill, 'Marketing y publicidad', None)
  n22 = _createGroup(FreelancerSkill, 'Branding', n1)
  _createChildren(FreelancerSkill, n22, [
    'Estudio y análisis de entorno',
    'Segmentación de mercado',
    'Conceptualización y diseño de identidad corporativa',
    'Arquitectura de marca',
    'Naming',
    'Brand Equity',
    'Diseño de logo e identidad visual',
    'Rediseño de marca - rebranding',
    'Posicionamiento y valores de marca',
  ])

  n22 = _createGroup(FreelancerSkill, 'Diseño y creatividad', n1)
  n333 = _createGroup(FreelancerSkill, 'Arte e ilustración', n22)
  _createChildren(FreelancerSkill, n333, [
    'Ilustración corporativa',
    'Ilustración artística',
    'Ilustración para libros',
    'Iconografía',
    'Diseño de personajes',
    'Storyboards',
    'Caricaturas',
    'Dibujos digitales',
    'Infografías',
    'Graffitis',
  ])
  n333 = _createGroup(FreelancerSkill, 'Dirección creativa', n22)
  _createChildren(FreelancerSkill, n333, [
    'Dirección creativa para campañas digitales',
    'Dirección creativa para campañas 360',
    'Dirección creativa de eventos',
    'Dirección creativa audiovisual',
    'Dirección creativa musical',
  ])
  n333 = _createGroup(FreelancerSkill, 'Diseño gráfico corporativo', n22)
  _createChildren(FreelancerSkill, n333, [
    'Diseño de empaques - Packaging',
    'Diseño de etiquetas',
    'Diseño editorial',
    'Diseño de presentaciones',
    'Diseño de menú (restaurants)',
    'Diseño de tarjetas',
  ])
  n333 = _createGroup(FreelancerSkill, 'Diseño publicitario', n22)
  _createChildren(FreelancerSkill, n333, [
    'Diseño de merchandising',
    'Diseño de brochures',
    'Diseño de flyers informativos',
    'Diseño de banners',
    'Diseño de catálogos',
    'Diseño y edición de imágenes',
    'Diseño para social media',
  ])

  n22 = _createGroup(FreelancerSkill, 'Audiovisuales y 3D', n1)
  n333 = _createGroup(FreelancerSkill, 'Fotografía', n22)
  _createChildren(FreelancerSkill, n333, [
    'Fotografía para redes sociales',
    'Fotografía de productos',
    'Fotografía de prendas y zapatería',
    'Fotografía de modelos',
    'Fotografía gastronómica',
    'Fotografía de bebés',
    'Retratos familiares',
    'Fotografía de matrimonios',
    'Fotografía de eventos',
    'Fotografía corporativa',
    'Fotografías 360º',
    'Fotografía industrial',
    'Fotografía publicitaria',
    'Retoque de fotografía digital',
  ])
  n333 = _createGroup(FreelancerSkill, 'Video', n22)
  _createChildren(FreelancerSkill, n333, [
    'Videos corporativos para empresas',
    'Producción y post-producción de videos',
    'Servicio de grabación de video 360º',
    'Videos publicitarios',
    'Videos animados',
    'Elaboración de tutoriales',
    'Cortometrajes',
    'Producción de audio',
    'Edición de vídeo',
    'Grabación de video',
    'Dirección de vídeo',
  ])
  n333 = _createGroup(FreelancerSkill, 'Audio', n22)
  _createChildren(FreelancerSkill, n333, [
    'Doblaje español-inglés',
    'Doblaje inglés-español',
    'Voz en off',
    'Voz para publicidad',
    'Songwriting',
    'Composición musical',
    'Producción musical',
    'Disc Jockey - DJ',
    'Vocalista',
    'Creación de jingles publicitario',
    'Creación de intros musicales',
    'Elaboración de podcasts',
    'Efectos de sonido',
    'Producción de audiolibros',
  ])
  n333 = _createGroup(FreelancerSkill, '3D', n22)
  _createChildren(FreelancerSkill, n333, [
    'Producción 3D',
    'Diseño en 3D',
    'Modelado en 3D',
    'Renderizado en 3D',
    'Animación en 3D',
    'Fotografía y recorridos 3D',
    'Arquitectura comercial',
    'Showrooms',
  ])
  n333 = _createGroup(
    FreelancerSkill,
    'Videojuegos, Realidad aumentada y virtual',
    n22)
  _createChildren(FreelancerSkill, n333, [
    'Experiencias publicitarias en Realidad Aumentada',
    'Experiencias publicitarias en Realidad Virtual',
    'Videojuegos publicitarios web 2D',
    'Videojuegos publicitarios para activaciones',
    'Videojuegos publicitarios 3D',
  ])

  n22 = _createGroup(FreelancerSkill, 'Redacción creativa y publicitaria', n1)
  _createChildren(FreelancerSkill, n22, [
    'Artículos y publicaciones de blog',
    'Escritura del curriculum vitae',
    'Corrección de textos y edición',
    'Escritura técnica',
    'Cartas de presentación',
    'Perfiles de LinkedIn',
    'Copywriting',
    'Ghostwriting',
    'Investigación y resúmenes',
    'Descripciones de productos',
    'Contenido de sitio web',
    'Escritura de guiones',
    'Redacción de discursos',
    'Redacción de podcasts',
    'Creación de diálogos',
    'Corrección de estilo',
    'Escritura de artículos',
    'Escritura creativa',
  ])
  n22 = _createGroup(FreelancerSkill, 'Generación de Tráfico', n1)
  _createChildren(FreelancerSkill, n22, [
    'Generación de contenido',
    'Producción de contenido audiovisual',
    'E-mailing',
    'Email Remarketing',
    'Retargeting a website',
    'Retargeting a productos visitados e-commerce',
  ])
  n22 = _createGroup(FreelancerSkill, 'Social Media', n1)
  _createChildren(FreelancerSkill, n22, [
    'Community Management',
    'Social listening avanzado',
  ])
  n22 = _createGroup(FreelancerSkill, 'Publicidad digital', n1)
  _createChildren(FreelancerSkill, n22, [
    'Marketing de influencers',
    'Relaciones públicas - PR',
    'Activaciones digitales',
    'Facebook Ads',
    'Google Ads',
    'Linkedin Ads',
    'Tinder Ads',
    'Tik Tok Ads',
    'Twitch Ads',
    'Youtube Ads',
    'Publicidad programática',
    'Growth Hacking',
    'Elaboración de Chatbots',
  ])
  n22 = _createGroup(FreelancerSkill, 'Posicionamiento SEO', n1)
  _createChildren(FreelancerSkill, n22, [
    'SEO Técnico, etiquetas, sitemaps, robots.txt',
    'Index optimization',
    'SEO Local',
    'SEO Ecommerce',
    'SEO para Startups',
    'SEO Internacional',
    'SEO para marca personal',
    'Consultoría SEO',
    'Auditoría SEO',
    'Redacción de artículos SEO',
  ])
  n22 = _createGroup(FreelancerSkill, 'Medición y optimización', n1)
  _createChildren(FreelancerSkill, n22, [
    'Media Tracking',
    'A/B Testing',
    'ROI',
    'Facebook insight',
    'Google Analytics',
    'Google Data Studio',
    'Hootsuite',
    'RD  Station',
    'Hubspot',
  ])

  n1 = _createGroup(FreelancerSkill, 'Diseño de experiencia', None)
  n22 = _createGroup(FreelancerSkill, 'Service Design', n1)
  _createChildren(FreelancerSkill, n22, [
    'Generación de modelos de negocio',
    'Sprint Design',
    'Ideación y diseño de experiencia TOBE',
    'Elaboración de Service Blueprint',
  ])
  n22 = _createGroup(FreelancerSkill, 'Design Research', n1)
  _createChildren(FreelancerSkill, n22, [
    'Entrevistas de profundidad',
    'Elaboración de encuestas',
    'Realización de Focus Groups',
    'Observación de campo',
  ])
  n22 = _createGroup(FreelancerSkill, 'Diseño UX', n1)
  _createChildren(FreelancerSkill, n22, [
    'Diseño y prototipado UX de aplicaciones móviles',
    'Diseño y prototipado UX de aplicaciones web',
    'Diseño y prototipado UX de websites corporativos',
    'Diseño y prototipado UX de e-commerce web',
    'Diseño y prototipado UX de e-commerce mobile',
    'Pruebas de usabilidad con usuarios',
    'Test Heurístico',
    'Testing A/B',
    'Auditoría UX',
    'Análisis e interpretación de analítica para la mejora del diseño',
  ])
  n22 = _createGroup(FreelancerSkill, 'Diseño UI', n1)
  _createChildren(FreelancerSkill, n22, [
    'Diseño UI de landing pages',
    'Diseño UI de aplicaciones móviles',
    'Diseño UI de aplicaciones web',
    'Diseño UI de websites corporativos',
    'Diseño UI de ecommerce web',
    'Diseño UI de ecommerce mobile',
    'Atomic Design',
    'Creación de guía de estilos digitales',
  ])

  n1 = _createGroup(FreelancerSkill, 'Desarrollo de software', None)
  n22 = _createGroup(FreelancerSkill, 'Business Analysis', n1)
  _createChildren(FreelancerSkill, n22, [
    'Arquitectura empresarial',
    'Arquitectura de aplicaciones',
    'Arquitectura de la información',
    'Modelamiento de procesos BPM',
    'Generación de procedimientos',
    'Modelamiento de negocio',
    'Deﬁnir la necesidad de negocio',
    'Crear Business Case',
    'Deﬁnir el alcance de la solución',
    'Especiﬁcar y modelar los requerimientos',
    'Análisis de los requerimientos no-funcionales',
    'Verificar y validar requerimientos',
    'Modelado del alcance',
    'Creación de Project Charter',
    'Generación de documentos PMBOK',
    'Elaboración de documentación funcional',
    'Elaboración de historias de usuario',
    'Delimitación de criterios de aceptación',
    'Diseño de métricas e indicadores',
    "Definición de KPI's",
    'Mejora contínua basada en Lean y Six Sigma',
  ])
  n22 = _createGroup(FreelancerSkill, 'IDE de desarrollo', n1)
  _createChildren(FreelancerSkill, n22, [
    'Eclipse',
    'Visual Studio Code',
    'Visual Studio',
    'Netbeans',
    'IntelliJ IDEA',
    'PyCharm',
    'Sublime',
    'Android Studio',
    'XCode',
    'WebStorm',
  ])
  n22 = _createGroup(
    FreelancerSkill,
    'Repositorios de código y versionamiento',
    n1)
  _createChildren(FreelancerSkill, n22, [
    'Github',
    'Bitbucket',
    'Apache Subversion',
    'TortoiseSVN',
    'GitLab',
  ])
  n22 = _createGroup(FreelancerSkill, 'Gestor de paquetes', n1)
  _createChildren(FreelancerSkill, n22, [
    'Maven',
    'Gradle',
    'NuGet',
    'Composer',
    'npm',
    'Yarn',
    'Bower',
    'pip',
    'Mamba',
    'Conda',
    'Anaconda',
    'PEAR',
    'SetupTools',
    'PECL',
    'Packagist',
  ])

  n22 = _createGroup(FreelancerSkill, 'Aplicativos Móviles', n1)
  n333 = _createGroup(FreelancerSkill, 'Desarrollo Android Nativo', n22)
  _createChildren(FreelancerSkill, n333, [
    'Java',
    'Kotlin',
  ])
  n333 = _createGroup(FreelancerSkill, 'Desarrollo iOS Nativo', n22)
  _createChildren(FreelancerSkill, n333, [
    'Objective-C',
    'Swift',
  ])
  n333 = _createGroup(FreelancerSkill, 'Desarrollo Híbrido', n22)
  _createChildren(FreelancerSkill, n333, [
    'Apache Cordova',
    'Phonegap',
    'Ionic',
  ])
  n333 = _createGroup(FreelancerSkill, 'Desarrollo Cross-Platform', n22)
  _createChildren(FreelancerSkill, n333, [
    'Xamarin',
    'React Native',
    'Flutter'])

  n22 = _createGroup(FreelancerSkill, 'Programación Frontend', n1)
  n333 = _createGroup(FreelancerSkill, 'Tecnologías Web', n22)
  _createChildren(FreelancerSkill, n333, [
    'HTML',
    'CSS',
    'Javascript',
    'Typescript',
    'Sass',
    'JQuery',
  ])
  n333 = _createGroup(FreelancerSkill, 'Frameworks', n22)
  _createChildren(FreelancerSkill, n333, [
    'Angular JS',
    'Angular CLI',
    'Knockout',
    'React JS',
    'Vue JS',
    'Vue CLI',
    'Bootstrap',
    'Material UI',
    'Bulma',
  ])
  n333 = _createGroup(FreelancerSkill, 'Manejo de estados', n22)
  _createChildren(FreelancerSkill, n333, [
    'Redux',
    'Vuex',
    'MobX',
    'React Hooks',
    'RxJS',
  ])

  n22 = _createGroup(FreelancerSkill, 'Programación .NET', n1)
  _createChildren(FreelancerSkill, n22, [
    'Mono Project',
  ])
  n333 = _createGroup(FreelancerSkill, 'Frameworks y lenguajes', n22)
  _createChildren(FreelancerSkill, n333, [
    'C#',
    'Visual Basic',
    'F#',
    '.NET 4+',
    '.NET 6',
    '.NET Core',
    '.NET MVC',
    '.NET Web API',
    '.NET SignalR',
    'Nunit',
    'Serilog',
    'nDaptive',
    'webDaptive',
    '.NET Dynamic Data',
    '.NET MVC',
  ])
  n333 = _createGroup(FreelancerSkill, 'Data Providers', n22)
  _createChildren(FreelancerSkill, n333, [
    'OLE DB',
    'Oracle',
    'ODBC',
    'CData',
    'Sybase',
    'MySQL',
    'Synergex',
    'Firebird',
    'Npgsql',
    'SQL Server Compact',
    'dotConnect',
    'SQL Server',
  ])
  n333 = _createGroup(FreelancerSkill, 'Data Access', n22)
  _createChildren(FreelancerSkill, n333, [
    'ADO .NET',
    'LINQ',
    'Entity Framework',
    'Active Record',
    'Nhibernate',
    'Dapper',
  ])
  n333 = _createGroup(FreelancerSkill, 'Web Services', n22)
  _createChildren(FreelancerSkill, n333, [
    'OData',
    'SOAP',
    'REST',
    'WCF Data Services',
    'WCF Services',
    '.NET Web Services',
    'JSON',
    '.NET Core Web Services',
    'ASP.NET Web APIs',
  ])
  n333 = _createGroup(FreelancerSkill, 'Mobile apps', n22)
  _createChildren(FreelancerSkill, n333, [
    'Xamarin',
    'MAUI',
  ])
  n333 = _createGroup(FreelancerSkill, 'Web Development', n22)
  _createChildren(FreelancerSkill, n333, [
    '.NET Core',
    '.NET Dynamic Data',
    '.NET AJAX',
    '.NET MVC',
    '.NET',
    'DevExpress',
    'DHTMLX',
    'Webix',
    '.NET AJAX CT',
    'Infragistics',
    'Telerik',
    '.NET Controls',
    'View2',
    'Razor pages',
    'Blazor Server',
    'PWAs',
    'JQuery',
    'Bootstrap',
    'Knockout',
    'Angular',
    'React JS',
    'DotVVM',
    'Blazor Client',
  ])
  n333 = _createGroup(FreelancerSkill, 'Desktop Applications', n22)
  _createChildren(FreelancerSkill, n333, [
    'WinForms',
    'WPF',
    'XAML',
    'Browser Applications',
    'Silverlight',
    'UWP',
  ])
  n333 = _createGroup(FreelancerSkill, 'Azure Components', n22)
  _createChildren(FreelancerSkill, n333, [
    'Functions',
    'Service Bus (messages/queues)',
    'App Services (Hosting)',
    'Application Insights (logging and telemetry)',
  ])
  n333 = _createGroup(FreelancerSkill, 'RTC Technologies', n22)
  _createChildren(FreelancerSkill, n333, [
    'WebRTC',
    'WebSockets',
  ])
  n333 = _createGroup(FreelancerSkill, 'Distributed Applications', n22)
  _createChildren(FreelancerSkill, n333, [
    'Enterprise Services',
    '.NET Remoting',
  ])
  n333 = _createGroup(FreelancerSkill, 'Security', n22)
  _createChildren(FreelancerSkill, n333, [
    'HTTPS/SSL',
    'NTLM',
    'X.509',
    'SSO',
    'Encryption',
    'Kerberos',
    'Auditing',
    'Logging',
    'OAuth 2.0',
    'JWT',
  ])
  n333 = _createGroup(FreelancerSkill, 'Tools', n22)
  _createChildren(FreelancerSkill, n333, [
    'Visual Studio',
    'SQL SERVER',
    'Visual Studio Code',
    'Azure DevOps',
    'Power BI',
  ])
  n333 = _createGroup(FreelancerSkill, 'Products', n22)
  _createChildren(FreelancerSkill, n333, [
    'Office 365',
    'BizTalk',
    'Microsoft Azure',
    'Amazon Web Services',
    'EC2Exchange Server',
    'MS Dynamics',
    'SharePoint',
  ])

  n22 = _createGroup(FreelancerSkill, 'Programación Java', n1)
  n333 = _createGroup(FreelancerSkill, 'Frameworks y lenguajes', n22)
  _createChildren(FreelancerSkill, n333, [
    'Java 6',
    'Java 8',
    'Java 11',
    'Java 17',
    'Java 18',
    'Scala',
    'Spring Web',
    'Spring MVC',
    'Spring Boot',
    'Apache Struts',
    'Hibernate',
    'Apache Wicket',
    'Dropwizard ',
    'Grails',
    'JavaServer Faces',
    'Play',
    'Apache Hadoop',
    'GWT',
    'Vaadin',
    'Spark',
    'Vert.X',
    'Jersey',
    'Jackson',
    'OSGi ',
    'Drools',
    'Apache Mina',
  ])
  n333 = _createGroup(FreelancerSkill, 'Servidor de aplicaciones', n22)
  _createChildren(FreelancerSkill, n333, [
    'Nginx',
    'Apache Tomcat',
    'LiteSpeed',
    'Guvicorn',
    'Glassfish',
    'WebSphere',
    'JBoss',
    'WebLogic',
  ])
  n333 = _createGroup(
    FreelancerSkill,
    'Conectores a base de datos y persistencia',
    n22)
  _createChildren(FreelancerSkill, n333, [
    'JPA',
    'JDO',
    'Mybatis',
    'JDBC',
    'ODBC',
  ])
  n333 = _createGroup(FreelancerSkill, 'Web development', n22)
  _createChildren(FreelancerSkill, n333, [
    'Servlet API',
    'JSP',
    'JDBC API',
    'Java Persistence API',
    'OpenXava',
    'Primefaces',
    'RichFaces',
    'Jasper Reports',
    'ATG',
    'Tapestry',
    'JQuery',
    'Bootstrap',
    'Knockout',
    'Angular',
    'React JS',
    'Vue JS',
    'MomentJs',
  ])
  n333 = _createGroup(FreelancerSkill, 'Desktop Applications', n22)
  _createChildren(FreelancerSkill, n333, [
    'AWT',
    'SWT',
    'JIDE',
    'Swing',
  ])
  n333 = _createGroup(FreelancerSkill, 'Pruebas', n22)
  _createChildren(FreelancerSkill, n333, [
    'JUnit',
    'JSUnit',
    'Jazmin',
    'Arquillian',
    'ServletUnit ',
    'JWebUnit',
    'Cucumber',
    'Serenity',
    'Cypress',
    'Robot Jython',
    'Karate-DSL',
    'Citrus',
    'Gauge',
    'Galen',
  ])

  n22 = _createGroup(FreelancerSkill, 'Programación PHP', n1)
  _createChildren(FreelancerSkill, n22, [
    'Laravel',
    'Symfony',
    'CodeIgniter',
    'Zend Framewor',
    'Yii (Framework)',
    'CakePHP',
    'Slim',
    'Phalcon',
    'FuelPHP',
    'Fat-Free Framework',
  ])
  n22 = _createGroup(FreelancerSkill, 'Programación Python', n1)
  _createChildren(FreelancerSkill, n22, [
    'Python Django',
    'Python CherryPy',
    'Python Tornado',
    'Python SqlAlchemy',
    'Python Jinja2',
  ])
  n22 = _createGroup(FreelancerSkill, 'Programación Ruby', n1)
  _createChildren(FreelancerSkill, n22, [
    'Ruby on rails',
  ])

  n22 = _createGroup(FreelancerSkill, 'Programación Javascript', n1)
  n333 = _createGroup(FreelancerSkill, 'NodeJS', n22)
  _createChildren(FreelancerSkill, n333, [
    'Express',
    'Mongoose',
    'Vanilla',
  ])

  n22 = _createGroup(FreelancerSkill, 'Bases de datos', n1)
  n333 = _createGroup(FreelancerSkill, 'Bases de datos relacionales', n22)
  _createChildren(FreelancerSkill, n333, [
    'MySQL',
    'Maria DB',
    'PostgreSQL',
    'MSSQL Server',
    'Oracle Database',
  ])
  n333 = _createGroup(FreelancerSkill, 'NoSQL', n22)
  _createChildren(FreelancerSkill, n333, [
    'MongoDB',
    'Cassandra',
    'Redis',
    'CouchDB',
    'Node4J',
    'Hazelcast',
  ])

  n22 = _createGroup(FreelancerSkill, 'DevOps', n1)
  n333 = _createGroup(FreelancerSkill, 'Continuous Deployment - CD', n22)
  _createChildren(FreelancerSkill, n333, [
    'Kubernetes',
    'Docker',
    'Terraform',
  ])
  n333 = _createGroup(FreelancerSkill, 'Continuous Integration - CI', n22)
  _createChildren(FreelancerSkill, n333, [
    'Jenkins',
    'Vercel',
    'Travis',
    'CircleCI',
    'Atlassian Bamboo',
    'Buddy',
    'GoCD',
  ])
  n333 = _createGroup(FreelancerSkill, 'Servidor de aplicaciones', n22)
  _createChildren(FreelancerSkill, n333, [
    'Apache',
    'Nginx',
    'Tomcat',
    'LiteSpeed',
    'Guvicorn',
    'Microsoft IIS',
  ])

  n22 = _createGroup(FreelancerSkill, 'Cloud Computing', n1)
  _createChildren(FreelancerSkill, n22, [
    'AWS',
    'DigitalOcean',
    'Microsoft Azure',
    'Google Cloud',
  ])

  n22 = _createGroup(
    FreelancerSkill,
    'Quality Assurance & Testing especializado',
    n1)
  _createChildren(FreelancerSkill, n22, [
    'Pruebas funcionales',
    'Pruebas de rendimiento',
    'Pruebas de estrés',
    'Pruebas de accesibilidad',
    'Pruebas de usabilidad',
    'Pruebas de seguridad',
  ])
  n333 = _createGroup(FreelancerSkill, 'Automatización de pruebas', n22)
  _createChildren(FreelancerSkill, n333, [
    'UiPath',
    'Selenium',
    'Appium',
    'Protractor',
  ])

  n22 = _createGroup(FreelancerSkill, 'Programación Web', n1)
  n333 = _createGroup(FreelancerSkill, 'Websites - CMS', n22)
  _createChildren(FreelancerSkill, n333, [
    'Maquetación HTML',
    'Wordpress',
    'Drupal',
    'Joomla',
    'Liferay',
  ])
  n333 = _createGroup(FreelancerSkill, 'Websites - E-commerce', n22)
  _createChildren(FreelancerSkill, n333, [
    'Woocommerce',
    'Prestashop',
    'Magento',
    'Shopify',
    'IBM WebSphere Commerce',
    'Adobe ecommerce',
    'Oracle ATG',
    'SAP Hybris',
    'VTEX',
    'Optimización y performance',
  ])
  n333 = _createGroup(FreelancerSkill, 'Websites - LMS', n22)
  _createChildren(FreelancerSkill, n333, [
    'Moodle',
    'Blackboard',
    'Plugins de Wordpress',
  ])
  n333 = _createGroup(FreelancerSkill, 'Websites - Intranets', n22)
  _createChildren(FreelancerSkill, n333, [
    'Sharepoint',
    'Drupal',
    'Moodle',
    'Plugins de Wordpress',
  ])
  _createChildren(FreelancerSkill, n22, [
    'Programación Salesforce',
  ])

  n22 = _createGroup(FreelancerSkill, 'Programación avanzada', n1)
  _createChildren(FreelancerSkill, n22, [
    'Linux development',
    'Assembler development',
    'Algoritmia avanzada para soluciones industriales',
    'Algoritmia avanzada para soluciones comerciales',
    'Matemáticas aplicada a la industria',
    'Inteligencia artificial',
    'Machine learning',
    'Deep learning',
  ])

  n22 = _createGroup(FreelancerSkill, 'Consultoría y programación ERP', n1)
  _createChildren(FreelancerSkill, n22, [
    'Microsoft Dynamics',
  ])
  n333 = _createGroup(FreelancerSkill, 'Oracle', n22)
  _createChildren(FreelancerSkill, n333, [
    'JD Edwards Enterprise One',
    'Oracle People Soft',
    'Oracle E-Business One',
  ])
  _createChildren(FreelancerSkill, n22, [
    'Infor',
  ])
  n333 = _createGroup(FreelancerSkill, 'SAP', n22)
  _createChildren(FreelancerSkill, n333, [
    'SAP ABAP',
    'SAP Fiori',
    'SAPUI5',
  ])
  n4444 = _createGroup(FreelancerSkill, 'SAP R3', n333)
  _createChildren(FreelancerSkill, n4444, [
    'FI: (Finanzas) Contabilidad Financiera',
    'CO: (Controlling) Control y Costos',
    'LO: (Logistics) Logística general',
    'SD: (Sales and Distribution) Ventas y Distribución',
    'MM: (Materials Management) Gestión de Materiales',
    'LE: (Logistics Execution) Ejecución de logística',
    'PP: (Production Planning) Planificación de la producción',
    'PS: (Project system) Sistema de Proyectos',
    'QM (Quality Management) Gestión de calidad',
    'HR (Human Resources) Recursos Humanos',
    'BC Basis Components',
  ])
  n4444 = _createGroup(FreelancerSkill, 'SAP HANA', n333)
  _createChildren(FreelancerSkill, n4444, [
    'Asset Management (Gestión de activos)',
    'Finance (Finanzas)',
    'Human Resources (Recursos humanos)',
    'Manufacturing (Fabricación)',
    'Maintenance, Repair, and Overhaul (Mantenimiento, reparación y revisión)',
    'R&D / Engineering (I+D / Ingeniería)',
    'Sales (Ventas)',
    'Service (Servicios)',
    'Supply Chain (Cadena de suministro)',
    'Analytics Technology (Tecnología analítica)',
    'Enterprise Technology (Tecnología empresarial)',
    'Projects (Proyectos)',
    'Database and Data Management (Base de datos y gestión de datos)',
  ])
  n4444 = _createGroup(FreelancerSkill, 'SAP Business One', n333)
  _createChildren(FreelancerSkill, n4444, [
    'Oportunidades',
    'Ventas',
    'Interlocutores comerciales',
    'Gestión de bancos',
    'Inventario',
    'Recursos',
    'Producción',
    'Compras',
    'Planificación de necesidades',
    'Servicio',
    'Recursos humanos',
    'Informes',
    'Gestión',
  ])
  n4444 = _createGroup(FreelancerSkill, 'Industrias específicas', n333)
  _createChildren(FreelancerSkill, n4444, [
    'Agriculture (Agricultura)',
    'Banking (La banca)',
    'Insurance (Aseguradoras)',
    'Oil & Gas (Petróleo y gas natural)',
    'Professional Services (Servicios profesionales)',
    'Public Sector (Sector público)',
    'Retail and Fashion (Retail y moda)',
    'Utilities (Servicios)',
    'SAP Waste & Recycling (Desperdicio y reciclaje)',
  ])

  n1 = _createGroup(FreelancerSkill, 'Desarrollo de videojuegos', None)
  n22 = _createGroup(FreelancerSkill, 'Lenguajes de programación', n1)
  _createChildren(FreelancerSkill, n22, [
    'C++',
    'C#',
    'Java',
    'Javascript',
    'Lua',
    'Python',
  ])
  n22 = _createGroup(FreelancerSkill, 'Desarrollo de videojuegos 2D', n1)
  _createChildren(FreelancerSkill, n22, [
    'Unreal Engine',
    'CryEngine',
    'Unity',
    'GameMaker',
    'Godot',
    'RPG Maker',
    'Cocos 2D',
    'Construct',
    'Stencyl',
    'Duality',
    'PlayCanvas',
    'CraftStudio',
    'Wimi 5',
    'GDevelop',
    'Murl Engine',
  ])
  n22 = _createGroup(FreelancerSkill, 'Desarrollo de videojuegos 3D', n1)
  _createChildren(FreelancerSkill, n22, [
    'Unity 3D',
    'Unreal Engine',
    'Pixel Art',
    'Pyxel Edit',
    'Piskel',
    'CryEngine',
    'Amazon Lumberyard',
    'Godot',
    'Urho3D',
    'Panda3D',
  ])
  n22 = _createGroup(FreelancerSkill, 'Plataforma del videojuego', n1)
  _createChildren(FreelancerSkill, n22, [
    'Mobile Android nativo',
    'Mobile iOS nativo',
    'Web',
    'Desktop',
  ])
  n22 = _createGroup(FreelancerSkill, 'Software para 3D', n1)
  _createChildren(FreelancerSkill, n22, [
    '3Dx Max Studio',
    'Blender',
    'Autodesk Maya',
    'Zbrush',
  ])
  n22 = _createGroup(FreelancerSkill, 'Motores de audio', n1)
  _createChildren(FreelancerSkill, n22, [
    'XAudio2',
    'Wwise',
    'FMOD',
    'Tela',
    'Miles Sound System',
    'AstoundSound',
  ])
  n22 = _createGroup(FreelancerSkill, 'Diseño para los videojuegos', n1)
  _createChildren(FreelancerSkill, n22, [
    'Diseño de personajes 2D',
    'Diseño de personajes 3D',
    'Diseño de escenarios 2D',
    'Diseño de escenarios 3D',
  ])
  n22 = _createGroup(FreelancerSkill, 'Jugabilidad', n1)
  _createChildren(FreelancerSkill, n22, [
    'Diseño de interacciones',
    'Creación de historias',
    'Gameflow',
    'Diseño de comportamientos',
    'Desarrollo de diálogos',
  ])

  n1 = _createGroup(FreelancerSkill, 'Business Intelligence', None)
  n22 = _createGroup(
    FreelancerSkill,
    'Estadística, minería y ciencia de datos',
    n1)
  _createChildren(FreelancerSkill, n22, [
    'SPSS',
    'Stata',
    'Lenguaje R',
    'Programación Python',
    'Programación Java',
    'Programación SQL',
    'Matlab',
    'SAS',
    'RapidMinder',
    'BigML',
    'SAS',
    'TIBCO',
    'Alteryx',
    'Knime',
    'Mathworks',
    'Hadoop',
    'Spark',
    'Hive',
    'HBase',
  ])
  n22 = _createGroup(FreelancerSkill, 'ETL', n1)
  _createChildren(FreelancerSkill, n22, [
    'IBM Websphere DataStage',
    'Microsoft Integration Services',
    'SAP Data Integrator',
    'Cognos Decisionstream',
    'Sunopsis',
    'Apache NiFi',
    'Streamsets',
    'Apache Airflow',
    'AWS Data Pipeline',
    'AWS Glue',
    'Talend',
    'Informatica Power Center',
    'AB Initio',
    'Pentaho',
    'Azure Data Factory',
    'SAS Dataflux',
  ])
  n22 = _createGroup(FreelancerSkill, 'Análisis y visualización de Datos', n1)
  _createChildren(FreelancerSkill, n22, [
    'SAP Business Objects',
    'Microsoft Reporting Services',
    'Microsoft Analysis Services',
    'Power BI',
    'Tableau',
    'Qlik',
    'Microstrategy',
    'Thoughtspot',
  ])

  n1 = _createGroup(FreelancerSkill, 'Traducción', None)
  _createChildren(FreelancerSkill, n1, [
    'Traducción inglés-español',
    'Traducción español-inglés',
    'Traducción español-quechua',
  ])


def _createGroup(FreelancerSkill, skill: str, parent):
  id = FreelancerSkill.objects.create(name=skill)
  if parent:
    parent.children.add(id)
  return id


def _createSkill(FreelancerSkill, skill: str, parent):
  id = FreelancerSkill.objects.create(name=skill)
  parent.children.add(id)


def _createChildren(FreelancerSkill, parent, children: List[str]):
  for child in children:
    _createSkill(FreelancerSkill, child, parent)


class Migration(migrations.Migration):

  dependencies = [
    ('sinek', '0005_freelancer_availability_freelancer_disponibility_and_more'),
  ]

  operations = [
    migrations.RunPython(MigrateDeleteFreelancerKnowledges),
    migrations.RunPython(MigrateDeleteTreeSkills),
    migrations.RunPython(MigrateSkillTree),
  ]
