# Generated by Django 4.0.3 on 2022-08-12 23:39

from django.db import migrations, models
import django.db.models.deletion


def MigrateDeleteFreelancerKnowledges(apps, schema_editor):
  FreelancerKnowledge = apps.get_model('sinek', 'FreelancerKnowledge')
  FreelancerKnowledge.objects.all().delete()


class Migration(migrations.Migration):

  dependencies = [
    ('sinek', '0006_skill_tree_update'),
  ]

  operations = [
    migrations.RunPython(MigrateDeleteFreelancerKnowledges),
    migrations.RemoveField(
      model_name='freelancerknowledge',
      name='name',
    ),
    migrations.AddField(
      model_name='freelancerknowledge',
      name='skill',
      field=models.ForeignKey(
        default=None,
        on_delete=django.db.models.deletion.CASCADE,
        to='sinek.freelancerskill'),
      preserve_default=False,
    )]
