# Generated by Django 4.0.3 on 2022-09-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinek', '0007_remove_freelancerknowledge_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='isOnboarded',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
