INITIAL_BUSINESSES = {
  'Abogados y notarías',
  'Administración pública',
  'Agroindustria, ganadería y curtiduría',
  'Alimentos, bebidas y tabaco',
  'Alquiler de Maquinaria',
  'Artesanía',
  'Automotriz',
  'Aviación y aeronáutica',
  'Banca, seguros, servicios financieros y AFP',
  'Biotecnología',
  'Belleza',
  'Correo',
  'Caucho y plástico',
  'Comercio minorista',
  'Comercializadoras e importadoras',
  'Construcción, cementeras y concreteras',
  'Cultura',
  'Diversión y esparcimiento',
  'Diseño y publicidad',
  'Educación',
  'Editoriales, impresión y librerías',
  'Energía, agua y electricidad',
  'Estilismo, cosmiatría y barbería',
  'Fabricación',
  'Forestal y silvicultura',
  'Gastronomía',
  'Hidrocarburos',
  'Inmobiliarias',
  'Hotelería y turismo',
  'Investigación, desarrollo y patentes',
  'Laboratorios farmacéuticos',
  'Logística nacional e internacional',
  'Manufactura',
  'Manejo de desperdicios y reciclaje',
  'Medios de comunicación',
  'Metalmecánica',
  'Minerales no metálicos',
  'Minería',
  'Moda y confección',
  'Papelería y empaquetadoras',
  'Pesca y acuicultura',
  'Plásticos y caucho',
  'Producción cinematográfica y musical',
  'Químicas',
  'Retail, tiendas por departamento y supermercados',
  'Robótica y domótica',
  'Servicios profesionales y consultorías',
  'Salud humana y animal',
  'Seguridad y defensa',
  'Siderurgia',
  'Tecnologías de la información',
  'Telecomunicaciones',
  'Transporte humano, público y privado',
  'Transporte marítimo, ferroviario y puertos',
  'Textiles y calzado',
  'Transporte humano'
}
