INITIAL_PROJECTS = {
  'Geolocalización',
  'Campaña publicitaria',
  'Distribución',
  'Transporte de productos',
  'Punto de venta',
  'Área Comercial',
  'Gestión de pedidos',
  'Facturación electrónica',
  'Firma digital',
  'Reconocimiento facial',
  'Reconocimiento de imágenes',
  'Monitoreo de pedidos',
  'Monitoreo con GPS',
  'Área de Logística',
  'Control de inventario',
  'Área de Almacén',
  'Área de Finanzas',
  'Área de Contabilidad',
  'Área de Tesorería',
  'Área de Compras',
  'Área de Proveedores',
  'Área de Suministros',
  'Área de Mantenimiento',
  'Área de Empaquetamiento',
  'Área de Tecnología',
  'Mantenimiento de maquinarias',
  'Mantenimiento de planta',
  'Mantenimiento de vehículos',
  'Área de Producción',
  'Área de Operaciones',
  'Área de Proyectos',
  'Área de Calidad',
  'Área de Reclutamiento y Selección',
  'Área de Recursos Humanos',
  'Evaluación del desempeño',
  'Gestión de Clima laboral',
  'Control de asistencia',
  'Payroll',
  'Gestión de la carga laboral',
  'Área Legal',
  'Seguridad industrial',
  'ERP a medida',
  'CRM a medida',
  'LMS a medida',
  'CMS a medida',
  'Intranet a medida',
  'Software de manejo de contratos',
  'Software documental',
  'Software para eventos',
  'Software para activaciones BTL',
  'Software de auditoría',
  'Seguimiento y control de proyectos',
  'Activaciones BTL con personal',
  'Campaña creativa',
  'Campaña 360',
  'Omnicanal'
}
