# Generated by Django 4.0.3 on 2022-12-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboard",
            name="process_link",
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="onboard",
            name="process_name",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
