# Generated by Django 4.0.3 on 2022-12-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboard", "0002_onboard_process_link_onboard_process_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q1",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q10",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q11",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q12",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q13",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q14",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q15",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q16",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q17",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q18",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q19",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q2",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q20",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q21",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q22",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q23",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q24",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q25",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q26",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q27",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q28",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q29",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q3",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q30",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q31",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q32",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q33",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q34",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q35",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q36",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q37",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q38",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q39",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q4",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q40",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q5",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q6",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q7",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q8",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
        migrations.AlterField(
            model_name="careeranchorsinput",
            name="q9",
            field=models.IntegerField(
                choices=[(1, ""), (2, ""), (3, ""), (4, ""), (5, ""), (6, "")]
            ),
        ),
    ]
