# Generated by Django 4.0.3 on 2022-12-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboard", "0003_alter_careeranchorsinput_q1_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AgilityLearningInput",
            new_name="ComplexInstructionsInput",
        ),
        migrations.RenameField(
            model_name="onboard",
            old_name="show_agility_learning",
            new_name="show_complex_instructions",
        ),
    ]
