name: Django CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Check code
      run: |
        pre-commit run --all-files
    - name: Run Tests
      run: |
        coverage run --source=neodash,onboard,customers --omit='*migrations*' manage.py test neodash onboard customers
    - name: Validate Coverage
      run: |
        coverage report -m --skip-covered --skip-empty --fail-under=100
